# Generated by Django 4.2.27 on 2026-01-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_installment_amount_bookstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(choices=[('Gen', 'General'), ('Sci', 'Scientific'), ('Lit', 'Literary')], default='Gen', max_length=3),
        ),
    ]
